/**
 * File is only for reference purposes
 */
export enum IngredientFilterCriterias {
  ALPHABETICAL_ASCENDING,
  ALPHABETICAL_DESCENDING,
  QUANTITY_ASCENDING,
  QUANTITY_DESCENDING,
  CREATION_DATE_ASCENDING,
  CREATION_DATE_DESCENDING,
}
