/**
 * File is only for reference purposes
 */
export enum RecipeFilterCriterias {
  ALPHABETICAL_ASCENDING,
  ALPHABETICAL_DESCENDING,
  CREATION_DATE_ASCENDING,
  CREATION_DATE_DESCENDING,
  PREPARATION_TIME_ASCENDING,
  PREPARATION_TIME_DESCENDING,
  DIFFICULTY_ASCENDING,
  DIFFICULTY_DESCENDING,
}
